services:
  service:
    image: wallet-app:latest
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}

  db:
    image: postgres:17.4
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  db_data:

