services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: db:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}

  db:
    image: postgres:17.4
    restart: "no"
    ports:
      - "7070:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  db_data:

