spring:
  application:
    name: WalletApp
  liquibase:
    change-log: db/changelog/changelog.yaml
    enabled: true
    liquibase-schema: wallet_app
    url: jdbc:postgresql://${DB_URL:*}
    user: ${DB_USERNAME:*}
    password: ${DB_PASSWORD:*}
  r2dbc:
    password: ${DB_PASSWORD:*}
    username: ${DB_USERNAME:*}
    url: r2dbc:postgresql://${DB_URL:*}
preliquibase:
  sql-script-references: classpath:db/init/init-database.sql