spring:
  application:
    name: WalletApp
  liquibase:
    change-log: db/changelog/changelog.yaml
    enabled: true
    liquibase-schema: wallet_app
  r2dbc:
    password: ${DB_USERNAME:*}
    username: ${DB_PASSWORD:*}
    url: r2dbc:postgresql://${DB_URL:*}


